spring.application.name=wazzup-backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/wazzup_contacts}
spring.datasource.username=${DB_USERNAME:wazzup_user}
spring.datasource.password=${DB_PASSWORD:wazzup_password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
server.port=${SERVER_PORT:8080}
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax
