spring.application.name=wazzup-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/wazzup_contacts
spring.datasource.username=wazzup_user
spring.datasource.password=wazzup_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true